//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yinxiang.Web.smes_functionName {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblfunctionid;
		protected global::System.Web.UI.WebControls.TextBox txtorgId;
		protected global::System.Web.UI.WebControls.TextBox txtfunctionName;
		protected global::System.Web.UI.WebControls.TextBox txtfunctionPath;
		protected global::System.Web.UI.WebControls.TextBox txtfunctionGroup;
		protected global::System.Web.UI.WebControls.TextBox txtcreater;
		protected global::System.Web.UI.WebControls.TextBox txtuseNum;
		protected global::System.Web.UI.WebControls.TextBox txtlastUser;
		protected global::System.Web.UI.WebControls.TextBox txtlastUseDate;
		protected global::System.Web.UI.WebControls.TextBox txtmemo;
		protected global::System.Web.UI.WebControls.TextBox txtfunctioncode;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
