//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yinxiang.Web.smes_functionName {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblfunctionid;
	protected global::System.Web.UI.WebControls.Label lblorgId;
	protected global::System.Web.UI.WebControls.Label lblfunctionName;
	protected global::System.Web.UI.WebControls.Label lblfunctionPath;
	protected global::System.Web.UI.WebControls.Label lblfunctionGroup;
	protected global::System.Web.UI.WebControls.Label lblcreater;
	protected global::System.Web.UI.WebControls.Label lbluseNum;
	protected global::System.Web.UI.WebControls.Label lbllastUser;
	protected global::System.Web.UI.WebControls.Label lbllastUseDate;
	protected global::System.Web.UI.WebControls.Label lblmemo;
	protected global::System.Web.UI.WebControls.Label lblfunctioncode;


       
    }
}
