//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yinxiang.Web.t_Item_XS_Base_New {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txt产品代码;
		protected global::System.Web.UI.WebControls.TextBox txt产品名称;
		protected global::System.Web.UI.WebControls.TextBox txt肉品系数;
		protected global::System.Web.UI.WebControls.TextBox txt人工系数;
		protected global::System.Web.UI.WebControls.TextBox txt车间类别;
		protected global::System.Web.UI.WebControls.TextBox txt备注;
		protected global::System.Web.UI.WebControls.TextBox txtOrderID;
		protected global::System.Web.UI.WebControls.TextBox txt气调系数;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
