//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yinxiang.Web.t_Item_XS_Base_New {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbl产品代码;
	protected global::System.Web.UI.WebControls.Label lbl产品名称;
	protected global::System.Web.UI.WebControls.Label lbl肉品系数;
	protected global::System.Web.UI.WebControls.Label lbl人工系数;
	protected global::System.Web.UI.WebControls.Label lbl车间类别;
	protected global::System.Web.UI.WebControls.Label lblFID;
	protected global::System.Web.UI.WebControls.Label lbl备注;
	protected global::System.Web.UI.WebControls.Label lblOrderID;
	protected global::System.Web.UI.WebControls.Label lbl气调系数;


       
    }
}
